//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SpeakerID.rc
//
#define IDS_MSGRECORD                   1
#define IDS_MSGNOMATCH                  2
#define IDS_MSGINVALIDNAME              3
#define IDC_RECDEV                      3
#define IDS_MSGNAME                     4
#define IDS_MSGTOOSHORT                 5
#define IDS_MSGPICK                     6
#define IDT_PLAYERTIMER                 101
#define IDD_SPEAKERID_DIALOG            102
#define IDT_RECORDERTIMER               102
#define IDR_MAINFRAME                   128
#define IDD_USERINFO                    129
#define IDD_USERPASS                    132
#define IDD_OPTIONS                     137
#define IDB_BK                          146
#define IDD_ABOUT                       151
#define IDC_USERSLIST                   1000
#define IDC_NEWUSER                     1001
#define IDC_MODIFYUSER                  1002
#define IDC_RECORD                      1002
#define IDC_REMOVEUSER                  1003
#define IDC_PLAY                        1003
#define IDC_STEP                        1004
#define IDC_OPTIONS                     1004
#define IDC_SMSG                        1005
#define IDC_ABOUT                       1005
#define IDC_MSGICON                     1006
#define IDC_SMSGICON                    1007
#define IDC_REPNUM                      1009
#define IDC_MINLEN                      1010
#define IDC_NAME                        1016
#define IDC_SECURITY                    1018
#define IDC_ME                          1019
#define IDC_DR                          1020
#define IDC_JHE                         1021
#define IDC_TH                          1022
#define IDC_DP                          1023
#define IDC_FC                          1024
#define IDC_CM                          1025
#define IDC_SB                          1026
#define IDC_FD                          1027
#define IDC_JM                          1028
#define IDC_CT                          1029
#define IDC_OSIL                        65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
